FROM golang:1.11-stretch as builder

RUN mkdir /hetzner-sb-notifier
COPY . /hetzner-sb-notifier/
WORKDIR /hetzner-sb-notifier

RUN chmod +x build.sh

RUN /hetzner-sb-notifier/build.sh linux
RUN ls -lth /hetzner-sb-notifier/builds

FROM centurylink/ca-certs
COPY --from=builder /hetzner-sb-notifier/builds /root
ENTRYPOINT ["/root/hetzner-sb-notifier_linux_amd64_1.0"]